enum TaskMutationTypes {
  ADD_LIST_TASK = 'ADD_LIST_TASK',
  CREATE_TASK_CREATION_GROUP = 'CREATE_TASK_CREATION_GROUP',
  DELETE_TASK = 'DELETE_TASK',
  MARK_TASK_INBOX = 'MARK_TASK_INBOX',
  MARK_TASK_SEEN = 'MARK_TASK_SEEN',
  MOVE_TASK = 'MOVE_TASK',
  REMOVE_LIST_TASK = 'REMOVE_LIST_TASK',
  UPDATE_TASK_PROPS = 'UPDATE_TASK_PROPS',
}

export default TaskMutationTypes;